import * as React from "react";
import { Route, Switch } from "react-router";

import "./App.scss";

import { Button } from "../../components/button/Button";
import { Header } from "../../components/header/Header";
import { Hero } from "../../components/hero/Hero";

class AppPage extends React.Component {
  public render() {
    return (
      <div className="app">
        <Header />
        <Hero>
          <h1 className="title">
            create-react-app-typescript-rewired-styleguidist
          </h1>
          <h2 className="subtitle">
            A sample for using react-styleguidist, TypeScript, generated by
            react-create-app with react-app-rewired.
          </h2>
          <Button>Click me</Button>
        </Hero>
      </div>
    );
  }
}

class AppPage2 extends React.Component {
  public render() {
    return (
      <div className="app">
        <Header />
        <Hero>
          <h1 className="title">Page others</h1>
          <h2 className="subtitle">Other page</h2>
          <Button>Click me</Button>
        </Hero>
      </div>
    );
  }
}
export const App = () => (
  <Switch>
    <Route exact path="/" component={AppPage} />
    <Route exact path="/challenges" component={AppPage2} />
  </Switch>
);
export default App;
